tenses:
  worked:   [working, worked]
  ate:      [eating, ate]
  watched:  [watching, watched]
  listened: [listening, listened]
  read:     [reading, read]

icons:
  listened: fa-music
  ate:      fa-cutlery
  watched:  fa-film
  worked:   fa-pencil
  read:     fa-book
  unknown:  fa-question
