development:
  adapter: postgresql
  encoding: UTF8
  database: finger_tweet_development
  pool: 5
  password:

test:
  adapter: postgresql
  encoding: UTF8
  database: finger_tweet_test
  pool: 5
  password:

production:
  adapter: postgresql
  encoding: UTF8
  database: finger_tweet_production
  pool: 5
  password:
